language: generic
dist: xenial

env:
  global:
    - INSTALL_EDM_VERSION=3.0.1
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - env: RUNTIME=3.6
  fast_finish: true

cache:
  directories:
    - "~/.cache"

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then sh -e ./install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  - edm install -y wheel click
install:
  - edm run -- python etstool.py install --runtime=${RUNTIME}
script:
  - edm run -- python etstool.py flake8 --runtime=${RUNTIME}
  - edm run -- python etstool.py test --runtime=${RUNTIME}
