build: false
skip_branch_with_pr: true
platform: x64

environment:
  global:
    PYTHONUNBUFFERED: "1"
    INSTALL_EDM_VERSION: "3.0.1"

  matrix:
    - RUNTIME: '3.6'

matrix:
  fast_finish: true

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.cache -> appveyor-clean-cache.txt
  - C:\Users\appveyor\AppData\Local\pip\Cache -> appveyor-clean-cache.txt

init:
  - ps: $Env:path = "C:/Enthought/edm;" + $Env:path
  - ps: md C:/Users/appveyor/.cache -Force

install:
  - install-edm-windows.cmd
  - edm install -y wheel click
  - edm run -- python etstool.py install --runtime=%RUNTIME%

test_script:
  - edm run -- python etstool.py flake8 --runtime=${RUNTIME}
  - edm run -- python etstool.py test --runtime=${RUNTIME}
