name: Run test suite (no EDM)

on: [pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        runtime: ['3.8', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Clone the source
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install local package
      run: python -m pip install .
    - name: Run style checks (including our own style checks)
      run: python -m flake8 .
    - name: Run tests
      run: python -m unittest -v
