name: Run test suite

on: [pull_request, workflow_dispatch]

env:
  INSTALL_EDM_VERSION: 3.4.0

jobs:
  test-with-edm:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        runtime: ['3.6', '3.8']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Clone the source
      uses: actions/checkout@v3
    - name: Set up EDM
      uses: enthought/setup-edm-action@v2
      with:
        edm-version: ${{ env.INSTALL_EDM_VERSION }}
    - name: Set up bootstrap Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install bootstrap packages
      run: python -m pip install click
    - name: Create EDM environment
      run: python etstool.py install --runtime=${{ matrix.runtime }}
    - name: Run style checks
      run: python etstool.py flake8 --runtime=${{ matrix.runtime }}
    - name: Run tests
      run: python etstool.py test --runtime=${{ matrix.runtime }}
